ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: Message.get_update() missing 1 required positional argument: 'data'
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: Message.get_update() missing 1 required positional argument: 'data'
ERROR:root:Erro ao processar atualizações para o bot 6961027858:AAHTlaLQ0TkjCu7JPwSceQ69V36rfWmK6UA: Message.get_update() missing 1 required positional argument: 'data'
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: Message.get_update() missing 1 required positional argument: 'data'
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: Message.get_update() missing 1 required positional argument: 'data'
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: Message.get_update() missing 1 required positional argument: 'data'
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: Message.get_update() missing 1 required positional argument: 'data'
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: Message.get_update() missing 1 required positional argument: 'data'
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: Message.get_update() missing 1 required positional argument: 'data'
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: Message.get_update() missing 1 required positional argument: 'data'
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: Message.get_update() missing 1 required positional argument: 'data'
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: Message.get_update() missing 1 required positional argument: 'data'
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: Message.get_update() missing 1 required positional argument: 'data'
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: Message.get_update() missing 1 required positional argument: 'data'
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: Message.get_update() missing 1 required positional argument: 'data'
ERROR:root:Erro ao processar atualizações para o bot 6961027858:AAHTlaLQ0TkjCu7JPwSceQ69V36rfWmK6UA: Message.get_update() missing 1 required positional argument: 'data'
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: Message.get_update() missing 1 required positional argument: 'data'
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: Message.get_update() missing 1 required positional argument: 'data'
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: Message.get_update() missing 1 required positional argument: 'data'
ERROR:root:Erro ao processar atualizações para o bot 6961027858:AAHTlaLQ0TkjCu7JPwSceQ69V36rfWmK6UA: Message.get_update() missing 1 required positional argument: 'data'
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: 'Temp' object has no attribute 'get_update'
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: 'Temp' object has no attribute 'get_update'
ERROR:root:Erro ao processar atualizações para o bot 6961027858:AAHTlaLQ0TkjCu7JPwSceQ69V36rfWmK6UA: 'Temp' object has no attribute 'get_update'
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: cannot unpack non-iterable NoneType object
ERROR:root:Erro ao processar atualizações para o bot 6961027858:AAHTlaLQ0TkjCu7JPwSceQ69V36rfWmK6UA: cannot unpack non-iterable NoneType object
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: 'text'
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: 'text'
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: 'text'
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: 'text'
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: cannot access local variable 'text' where it is not associated with a value
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: Message.identificar_cep() takes 1 positional argument but 2 were given
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: Message.identificar_cep() takes 1 positional argument but 2 were given
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: 'NoneType' object has no attribute 'group'
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: Message.calcular_distancia_entre_ceps() missing 1 required positional argument: 'cep2'
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: list index out of range
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: 'Message' object has no attribute 'run_calculo_cep'
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: cannot access local variable 'i' where it is not associated with a value
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: [Errno 2] No such file or directory: 'data/p.jpg'
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: [Errno 2] No such file or directory: 'data/p.jpg'
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I/sendMessage (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000022C8F030B60>, 'Connection to api.telegram.org timed out. (connect timeout=None)'))
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: 'message'
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: 'text'
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: 'text'
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: 'message'
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: Message.get_message() takes 2 positional arguments but 3 were given
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: 'message'
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: 'message'
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: 'message'
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: 'message'
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: 'message'
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: 'message'
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: 'message'
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: 'message'
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: 'message'
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: 'message'
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: 'message'
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: 'message'
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: 'message'
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: 'message'
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: 'message'
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: 'text'
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: 'text'
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: 'int' object is not subscriptable
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: [Errno 2] No such file or directory: 'data/client.txt'
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: [Errno 2] No such file or directory: 'data/client.txt'
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: [Errno 2] No such file or directory: 'data/client.txt'
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: [Errno 2] No such file or directory: 'data/client.txt'
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: Unknown format code 'f' for object of type 'str'
ERROR:root:Erro ao processar atualizações para o bot 6729902739:AAGdX2ekGn4GeIjx7tAGxA4quCjCWX_Fo4I: Unknown format code 'f' for object of type 'str'
